apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fintech-app.fullname" . }}
  labels:
    {{- include "fintech-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.MISTRAL_API_KEY }}
  MISTRAL_API_KEY: {{ .Values.secrets.MISTRAL_API_KEY | b64enc }}
  {{- end }}
  {{- if .Values.secrets.DB_PASSWORD }}
  DATABASE_URL: {{ printf "postgresql://postgres:%s@%s:%d/%s" .Values.secrets.DB_PASSWORD .Values.database.host .Values.database.port .Values.database.name | b64enc }}
  {{- end }}
  {{- if .Values.secrets.REDIS_AUTH_TOKEN }}
  REDIS_URL: {{ printf "redis://:%s@%s:%d" .Values.secrets.REDIS_AUTH_TOKEN .Values.redis.host .Values.redis.port | b64enc }}
  {{- end }}
